#!/usr/bin/env node
// Reads .env (local) or process.env (CI/Netlify) and writes src/environments/environment.ts (gitignored).
// Never commit the generated file — API keys must not enter source control.

const fs   = require('fs');
const path = require('path');

const envPath = path.resolve(__dirname, '../.env');
const outPath = path.resolve(__dirname, '../src/environments/environment.ts');

const vars = {};

if (fs.existsSync(envPath)) {
  const raw = fs.readFileSync(envPath, 'utf8');
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    vars[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
} else {
  console.log('No .env file found — reading from process.env (CI/Netlify mode).');
}

const required = ['ALPACA_API_KEY', 'ALPACA_SECRET_KEY', 'ALPACA_DATA_URL'];
for (const key of required) {
  if (!vars[key] && process.env[key]) vars[key] = process.env[key];
}

const missing = required.filter(k => !vars[k]);
if (missing.length) {
  console.error(`ERROR: Missing required env keys: ${missing.join(', ')}`);
  process.exit(1);
}

const isCI = !fs.existsSync(envPath);
const content = `// AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.
export const environment = {
  production: ${isCI},
  alpaca: {
    apiKey:    '${vars.ALPACA_API_KEY}',
    secretKey: '${vars.ALPACA_SECRET_KEY}',
    dataUrl:   '${vars.ALPACA_DATA_URL}',
  },
};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log(`✓ environment.ts written`);
