#!/usr/bin/env node
// Reads .env and writes src/environments/environment.ts (gitignored).
// Never commit the generated file — API keys must not enter source control.

const fs   = require('fs');
const path = require('path');

const envPath = path.resolve(__dirname, '../.env');
const outPath = path.resolve(__dirname, '../src/environments/environment.ts');

if (!fs.existsSync(envPath)) {
  console.error('ERROR: .env file not found. Copy .env.example to .env and fill in your keys.');
  process.exit(1);
}

const raw  = fs.readFileSync(envPath, 'utf8');
const vars = {};

for (const line of raw.split('\n')) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) continue;
  const eq = trimmed.indexOf('=');
  if (eq === -1) continue;
  vars[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
}

const required = ['ALPACA_API_KEY', 'ALPACA_SECRET_KEY', 'ALPACA_DATA_URL'];
const missing  = required.filter(k => !vars[k]);
if (missing.length) {
  console.error(`ERROR: Missing required .env keys: ${missing.join(', ')}`);
  process.exit(1);
}

const content = `// AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.
// Source: .env (gitignored). Re-run \`node scripts/generate-env.js\` after changing .env.
export const environment = {
  production: false,
  alpaca: {
    apiKey:    '${vars.ALPACA_API_KEY}',
    secretKey: '${vars.ALPACA_SECRET_KEY}',
    dataUrl:   '${vars.ALPACA_DATA_URL}',
  },
};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log(`✓ environment.ts written`);
